domain/urls.py
from django.urls import path
from domain import views

urlpatterns = [
    path("", views.index, name="index"),
    path("results/", views.results, name='results'),
    path("subdomains/", views.get_subdomains, name='subdomains'),
    path("domains/", views.get_search_concepts, name='domains'),
    path("configurations/", views.modify_configurations, name='configurations'),
    path("add_filter/<str:filter_value>/<str:filter_action>/", views.add_filter, name='add_filter'),
]

qa_system/urls.py
from django.contrib import admin
from django.urls import include, path
from account import views as account
from questions import views as questions
urlpatterns = [
    path('admin/', admin.site.urls),
    path('domain/', include(('domain.urls', 'domain'), namespace='domain')),
    path('login/', include(('account.urls', 'account'), namespace='login')),
    path('questions/', include(('questions.urls', 'questions'), namespace='questions')),
    path('', account.loginPage, name='login'),
]

domain/views.py
import os
import time
import json
import requests
import wikipedia
import re
import time
import torch
import concurrent.futures
from django.shortcuts import render
from SPARQLWrapper import JSON, SPARQLWrapper
from django.shortcuts import render
from django.http import JsonResponse
from urllib.parse import quote
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import pandas as pd
from sentence_transformers import SentenceTransformer
from django.http import JsonResponse
from concurrent.futures import ProcessPoolExecutor
from haystack.nodes import TextConverter, PreProcessor
from haystack.nodes import PreProcessor
import pandas as pd
from transformers import AutoTokenizer
from haystack.nodes import TextConverter, PreProcessor
from pymilvus import (
    connections,
    Collection,
)
# Global variables
# Endpoint to make the query
endPoint = "https://dbpedia.org/sparql"
sparql = SPARQLWrapper(endPoint)
# Final paths to save the CSV files
ruta_del_csv = '..\\csv\\dominioFinalTesis.csv'
ruta_del_csv_spliteado = '..\\csv\\dominioFinalSpliteadoTesis.csv'


# Query endpoint and parse as JSON
def get_results(query):
    sparql.setQuery(query)
    sparql.setReturnFormat(JSON)
    results = sparql.query().convert()
    return results

def create_collection():
    from pymilvus import (
        connections,
        FieldSchema,
        CollectionSchema,
        DataType,
        Collection,
    )

    # Especifica la ruta del archivo CSV
    connections.connect("default", host="localhost", port="19530")

    din = 768

    collection_name = 'prueba_final_3_tesis'

    fields=[
        FieldSchema(name='id', dtype=DataType.INT64, is_primary=True, auto_id=True),
        FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, dim=din),
        FieldSchema(name='metadata', dtype=DataType.JSON)
    ]
            
    schema = CollectionSchema(fields)
    collection = Collection(name=collection_name, schema=schema)

    index_params = {
    "metric_type":"COSINE",
    "index_type":"FLAT"
    }

    collection = Collection(collection_name)
    collection.create_index(
        field_name="embedding", 
        index_params=index_params
    )

def index(request):
    #ruta_del_csv = 'csv\\dominioFinalTesis.csv'
    ruta_del_csv = 'csv\\dominioFinalSpliteado.csv'
    ruta_del_csv_spliteado = 'csv\\dominioFinalSpliteadoTesis.csv'
    # Get all the subdomains when the user clicks Send
    if request.method == 'POST':
        sections = []
        selectedValues = request.POST.get('valores_seleccionados')
        selectedValues = json.loads(selectedValues)
        lista = []

        lista += get_links(selectedValues)
        print("Links relacionados  ", len(lista))
        tiempo_inicial = time.time()
        with concurrent.futures.ProcessPoolExecutor(max_workers=30) as executor:
            futures = [executor.submit(
                get_page_sections, item['id_wiki']['value']) for item in lista]
            for num, future in enumerate(concurrent.futures.as_completed(futures)):
                sections += future.result()
        df = pd.DataFrame(sections, columns=[
                          'PageURL', 'Title', 'CreationDate', 'Seccion', 'Subseccion', 'Contenido', 'WikipageID', 'LastModified'])
        df.to_csv(ruta_del_csv, index=False)
        tiempo_final = time.time()

        # Calcular la duración total
        duracion_total = tiempo_final - tiempo_inicial
        print("Se demoro un tiempo de ", duracion_total,
              " segundos en obtener el contenido de wikipedia")

        tiempo_final = results(request, len(lista))

        # Subir datos a milvis
        inicio = time.time()
        ruta_del_csv = '.\\csv\\dominioFinalSpliteado.csv'

        df = pd.read_csv(ruta_del_csv_spliteado)
        df = df

        connections.connect("default", host="localhost", port="19530")
        collection_name = 'prueba_final_3_tesis'

        # Verificar si la colección existe
        try:
            collection = Collection(collection_name)
        except Exception as e:
            create_collection()

        
        collection = Collection(name=collection_name)
        
        index_params = {
            "metric_type":"COSINE",
            "index_type":"FLAT"
        }
        collection.create_index(
            field_name="embedding", 
            index_params=index_params
        )
        print([index.params for index in collection.indexes])
        #retriever = SentenceTransformer("sentence-transformers/all-mpnet-base-v2", device='cuda')
        retriever = SentenceTransformer("sentence-transformers/all-mpnet-base-v2", device='cpu')
        collection.load()

        df.fillna("", axis=1, inplace=True)
        
        for index, row in df.iterrows():
            print('==== ITER ========', index)
            emb = retriever.encode(row["split"]).tolist()
            meta = row.to_dict()
            to_upsert = {'embedding': emb, 'metadata': meta}
            collection.insert(data=[to_upsert])
        fin = time.time()
        print("Se demoro un tiempo de ", fin - inicio,
              " segundos en subir los datos a milvus")
        return render(request, 'results.html', {'contador': len(lista), 'tiempo_final': tiempo_final})
    return render(request, 'index.html')


def results(request, contador):
    start = time.time()
    split_content_haystack(ruta_del_csv)
    end = time.time()
    final = end - start
    print("Se demoro un tiempo de ", final,
          " segundos spliteand el contenido con haystack")
    return (final)
# Obtain the primary search concepts


def get_search_concepts(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        concepto = request.GET.get('term')
        tipo = request.GET.get('tipo')
        with open('global_config/filters.txt', 'r') as filters_file:
            data = filters_file.readline()
        data = data.split(";")
        data.pop()

        if concepto is not None and concepto != '':
            if tipo == '0':
                query = """
                SELECT DISTINCT ?r (COUNT(?concepts) AS ?conceptsCount)
                WHERE {
                ?r rdf:type skos:Concept; rdfs:label ?label.
                ?r ^skos:broader{1} ?concepts .
                FILTER(CONTAINS(str(?r), "%s"))
                FILTER(LANG(?label) = "en")
                }
                GROUP BY ?r
                HAVING(COUNT(?concepts) > 5)
                ORDER BY DESC(?conceptsCount)
                """ % (concepto)
            elif tipo == '1':
                filters = ""
                for filter_item in data:
                    filters += f"FILTER(!CONTAINS(str(?label), '{
                        filter_item.strip()}'))\n"
                query = """
                    SELECT DISTINCT ?r
                    WHERE
                    {
                        ?r rdf:type skos:Concept; rdfs:label ?label.
                        ?c skos:broader ?r.
                        FILTER CONTAINS(?label, "%s").
                        FILTER (LANG(?label) = "en").
                        %s
                    }
                    GROUP BY ?r ?label HAVING (COUNT(*) > 2)
                    ORDER BY DESC(COUNT(?r))
                    """ % (concepto, filters)
            resultados = get_results(query)
            opciones = [
                {"id": item["r"]["value"], "text": item["r"]["value"]}
                for item in resultados["results"]["bindings"]
            ]
            return JsonResponse({"results": opciones}, safe=False)
        else:
            return JsonResponse({"results": []}, safe=False)
    else:
        return JsonResponse({"error": "Invalid request. Only AJAX requests are allowed."}, status=400)


def get_subdomains(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        concepto = request.GET.get('selectedValue')
        nivel = request.GET.get('level')
        resultados = []
        nivel = request.GET.get('level') if request.GET.get(
            'level') != None else '0'
        if nivel == '0':
            dominiosSeleccionados = concepto.split("Category:", 1)[1]
            resultado = get_reource_query(dominiosSeleccionados, nivel)
            resultados.append(resultado)
        else:
            dominiosSeleccionados = request.POST.getlist('subdominios')
            dominiosSeleccionados = request.GET.getlist('selectedValue[]')
            for dominio in dominiosSeleccionados:
                dominio = dominio.split(":")[-1]
                resultado = get_reource_query(dominio, nivel)
                resultados.append(resultado)

        if resultados:
            lista = []
            for resultado in resultados:
                for item in resultado:
                    url = item["c1"]["value"]
                    clave = url.split(":")[-1]
                    lista.append(clave)
            json_data = json.dumps(lista)
            return JsonResponse(json_data, safe=False)
    return JsonResponse({'error': 'No se pudo procesar la solicitud'})


def get_reource_query(resource, level):
    resource = re.sub(r"([,()/.'])", r'\\\1', resource)

    with open('global_config/filters.txt', 'r') as filters_file:
        data = filters_file.readline()
        data = data.split(";")
        data.pop()

        filters = ""
        for filter_item in data:
            filters += f"FILTER(!CONTAINS(str(?label), '{
                filter_item.strip()}'))\n"
    query = """
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    PREFIX dct: <http://purl.org/dc/terms/>

    select distinct ?level ?r ?c1
        {
            {VALUES (?r ?level) {(dbc:%s + %s)}
                ?r ^skos:broader{1} ?c1.
                ?c1 rdfs:label ?label.
            FILTER(LANG(?label) = "en")
            %s           
        }
    
    }    
    """ % (resource, str(level), filters)

domain/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    {% block stylesheets %}{% endblock stylesheets %}
    <style>
        body {
            background-color: #f2f2f2;
            padding: 20px;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        a {
            text-decoration: none;
            color: #f2f2f2;
        }
        h1 {
            color: #333;
        }
        form {
            margin-top: 20px;
        }

    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">App - Creation of Wikipedia-based corpus</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'domain:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'domain:configurations' %}">Configuration</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    

<div class="container">
    {% block content %}
    {% endblock %}
</div>
{% block scripts %}
{% comment %} <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script> {% endcomment %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
{% endblock %}

</body>
</html>

domain/templates/configurations.html
{% extends "base.html" %}
{% block title %}
  Filters
{% endblock title %}
{% block content %}
  {% block stylesheets %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  {% endblock stylesheets %}
  <h1>Global Settings</h1>
  <div class="container-filters">
    <h2>Filters: words that are not expected to be in concept names.</h2>
    <ul class="list-group">
      {% for filter in data_list %}
        <li id="filterItem{{ filter }}"
            class="list-group-item d-flex justify-content-between align-items-center">
          {{ filter }}
          <span class="badge badge-primary badge-pill">
            <a href="#" onclick="deleteFilter('filterItem{{ filter }}')">Delete</a>
          </span>
        </li>
      {% endfor %}
    </ul>
    <div class="input-group mb-3">
      <input type="text"
             class="form-control"
             id="newFilterInput"
             placeholder="Enter a new filter"
             aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary"
                id="addFilterButton"
                type="button"
                onclick="addFilter">Add</button>
      </div>
    </div>
  </div>
{% endblock content %}
{% block scripts %}
  <script>
  document.addEventListener('DOMContentLoaded', function () {
    const addFilterButton = document.getElementById('addFilterButton');
    const newFilterInput = document.getElementById('newFilterInput');
    const filterList = document.querySelector('.list-group');

    addFilterButton.addEventListener('click', function () {
      const newFilterValue = newFilterInput.value.trim();
      if (newFilterValue) {
        // Agregar el nuevo filtro a la lista en el frontend
        const newFilterItem = document.createElement('li');
        newFilterItem.className = 'list-group-item d-flex justify-content-between align-items-center';
        newFilterItem.innerHTML = `
        ${newFilterValue}
        <span class="badge badge-primary badge-pill">
          <a href="#">Eliminar</a>
        </span>
      `;
        filterList.appendChild(newFilterItem);
        // Limpiar el campo de entrada
        newFilterInput.value = '';
      }
    });
  });
  function addFilter() {
    newFilter = $("#newFilterInput").val();
    data = { filter: newFilter };
    $.ajax({
      url: "{% url 'domain:add_filter' 'newFilter' 'add' %}".replace('newFilter', newFilter),
      data: data,
      success: function (response) {
        console.log(response)
      }
    })
  }

  function deleteFilter(deleteLi) {
    deleteItem = deleteLi.innerText.split("\n")[0]
    $.ajax({
      url: "{% url 'domain:add_filter' 'deleteItem' 'delete' %}".replace('deleteItem', deleteItem),
      success: function (response) {
        $(deleteLi).remove();
      }
    })
  }
  </script>
{% endblock scripts %}

domain/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Root Concept{% endblock title %}
{% block stylesheets %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <link rel="stylesheet" href="{% static 'styles/get_domain.css' %}"/>
{% endblock stylesheets %}
{% block content %}
    <h1>Enter the root concept</h1>
    <form id="miFormulario" method="post">
        {% csrf_token %}
        <div class="domain-container">
            <select class="mb-3 dominio" name="dominio"></select>
            <label>Filter</label>
            <select class="filter" name="filter" id="filter">
                <option value="0">URI (_)</option>
                <option value="1">Tag ( )</option>
            </select>
        </div>
        <select style="margin-top: 20px"
                class="subdominios"
                name="subdominios"
                multiple="multiple"></select>
        <input type="hidden" name="contador" id="contador" value="0">
        <input type="hidden" name="valores_seleccionados" id="valores_seleccionados">
        <div>
            <input style="margin-top: 20px"
                   type="button"
                   id="masSubdominios"
                   value="Get more concepts">
            <input type="submit" id="enviarTodo" value="Send">
        </div>
    </form>
    <div class="modal" tabindex="-1" role="dialog" id="loadingModal" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-body">
              <div class="d-flex justify-content-center align-items-center flex-column">
                <p>Loading...</p>
                <img width="50px" height="50px" src="{% static 'images/Loading.gif' %}" alt="Loading...">
              </div>
            </div>
          </div>
        </div>
      </div>
    <p id="resultado"></p>
{% endblock content %}
{% block scripts %}
{{ block.super }}
    <script>
    $(document).ready(function () {
        $('.filter').select2({
            width: '10%',
        });
        
        let valoresSeleccionados = [];
        
        $('.dominio').select2({
            closeOnSelect: true,
            placeholder: 'Domain',
            width: "80%",
            sorter: data => data.sort((a, b) => a.text.localeCompare(b.text)),
            ajax: {
                url: "{% url 'domain:domains' %}",
                delay: 1000,
                data: function (params) {
                    return {
                        'term': params.term,
                        'tipo': $("#filter").val(),
                    };
                },
                processResults: function (data) {
                    var options = [];
                    $.each(data.results, function (index, item) {
                        options.push({
                            id: item.id,
                            text: item.text
                        });
                    });
                    return {
                        results: options
                    };
                }

            }
        });

        $('.dominio').on('change', function (e) {
            var selectedValue = $(this).val();
            console.log("Valor seleccionado:", selectedValue); // Imprimir el valor seleccionado
            var params = {
                selectedValue: selectedValue,
            };
            $.ajax({
                url: '{% url "domain:subdomains" %}',
                data: params,       
                success: function (response) {
                    var select = $('.subdominios');
                    select.empty();
                    var data = JSON.parse(response);

                    // Iterar sobre el objeto data
                    $.each(data, function (index, value) {
                        select.append($('<option></option>').val(value).text(value));
                    });
                    // Establecer los valores seleccionados en función de los valores devueltos por el view
                    select.val(data);
                    select.trigger('change');
                }
            });
        
        });
        
        $('#masSubdominios').click(function (event) {
            event.preventDefault();
            var select = $('.subdominios');
            var nuevosValoresSeleccionados = select.val();
            valoresSeleccionados = valoresSeleccionados.concat(nuevosValoresSeleccionados);
            $('#valores_seleccionados').val(JSON.stringify(valoresSeleccionados));
            var selectedValue = $(".subdominios").val();
            console.log("Valor seleccionado:", selectedValue); // Imprimir el valor seleccionado
            var params = {
                selectedValue: selectedValue,
                level: "1",
            };
            $.ajax({
                url: '{% url "domain:subdomains" %}',
                data: params,
                beforeSend: function() {
                    // Mostrar el modal de carga
                    $("#loadingModal").modal('show');
                },
                success: function (response) {
                    var select = $('.subdominios');
                    select.empty();
                    var data = JSON.parse(response);
                    // Iterar sobre el objeto data
                    $.each(data, function (index, value) {
                        select.append($('<option></option>').val(value).text(value));
                    });
                    // Establecer los valores seleccionados en función de los valores devueltos por el view
                    select.val(data);
                    select.trigger('change');
                },
                complete: function() {
                    // Ocultar el modal de carga
                    $("#loadingModal").modal('hide');
                }
            });
        });

        $('#miFormulario').submit(function (event) {
            event.preventDefault();  // Evitar el envío normal del formulario
            var select = $('.subdominios');
            var nuevosValoresSeleccionados = select.val();
            valoresSeleccionados = valoresSeleccionados.concat(nuevosValoresSeleccionados);
            // Almacenar los valores seleccionados en el campo oculto
            $('#valores_seleccionados').val(JSON.stringify(valoresSeleccionados));
            // Mostrar el modal de carga
            $("#loadingModal").modal('show');
            $(this).unbind('submit').submit();
        });

        $('.subdominios').select2({
            closeOnSelect: false,
            placeholder: 'Select the subdomains',
            width: "100%",
            sorter: data => data.sort((a, b) => a.text.localeCompare(b.text)),
        });

        $('#masSubdominios').click(function () {
            var contador = $('#contador');
            contador.val(parseInt(contador.val()) + 1);
        });
    });
    </script>
{% endblock scripts %}

domain/templates/results.html
{% extends "base.html" %}
{% block title %}
    Contenido
{% endblock title %}
{% block stylesheets %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% endblock stylesheets %}
{% block content %}
    <div>
        <p>Se encontraron {{ contador }} enlaces relacionados</p>
        <p>Se demoro un timepo de {{ tiempo_final }} segundos</p>
    </div>
{% endblock content %}